name: A workflow for my Hello World App
on: push

jobs:
  build:
    ## Name the same as GitHub Actions CI
    name: Hello world action
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Network
        run: |
          docker network create --driver bridge mongoBridge
          docker pull mongo
          docker run -d --name mongodb-server --network mongoBridge mongo
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Build Docker Image
        run: docker build -t devopsimage .
      - name: Run image
        run: docker run --network mongoBridge --name devopscontainer -d devopsimage
      - name: view logs
        run: docker logs devopscontainer
